#include "legs.h"
#include "board.h"

void initLegs(void) {
  GPOUTPUT(LEG_A_DOWN); GPCLEAR(LEG_A_DOWN);
  GPOUTPUT(LEG_A_UP);   GPCLEAR(LEG_A_UP);
  GPOUTPUT(LEG_B_DOWN); GPCLEAR(LEG_B_DOWN);
  GPOUTPUT(LEG_B_UP);   GPCLEAR(LEG_B_UP);

  GPINPUT(LEG_A_SENSE); GPSET(LEG_A_SENSE);
  GPINPUT(LEG_B_SENSE); GPSET(LEG_B_SENSE);
}
